#+TITLE:     Groups, tags, and snp.picker
#+AUTHOR:    Chris Wallace
#+EMAIL:     chris.wallace@cimr.cam.ac.uk
#+DATE:      2014-04-25 Fri
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:(not LOGBOOK) todo:t pri:nil tags:t

#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:
#+LINK_HOME:
#+XSLT:

#+latex_header: \usepackage{fullpage}
#+latex: %\VignetteIndexEntry{Groups, tags, and snp.picker}

#+begin_html
<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{Groups, tags, and snp.picker}
-->
<font color="grey">
*Chris Wallace // [web](http://www-gene.cimr.cam.ac.uk/staff/wallace) // [email](mailto:chris.wallace at cimr.cam.ac.uk)*  
</font>
#+end_html

* Grouping SNPs

We often (usually) cannot resolve an association to a single causal
variant, and one of the aims of GUESSFM is to generate groups of SNPs,
one of which is likely to be causal.

* The groups and tags classes
The =groups= and =tags= classes are two ways to represent the same
information, but use different structures which might be more
convenient for one function or another.

#+BEGIN_SRC R :ravel
library(GUESSFM)
showClass("groups")
showClass("tags")
#+END_SRC

* Automatic group building based on marginal posterior probabilities
Once models have been fitted, we can average over them to find
marginal posterior probabilities for each SNP.  With the assumption
that SNPs in a group should display the following properties:
- the sum of MPI should be no more than 1
- SNPs in a group should not occur in the same model together (very
  often)
- SNPs in a group should be correlated (r^2), and the MPI should tail
  off from the primary SNP with r^2

=snp.picker()= aims to do this is an automated manner, given the summary
of a GUESS run and a genotype dataset from which r^2 may be
calculated.  It returns an object of class =snppicker= which is an
extension of the =groups= class and contains information to allow
plotting of the relationship between r^2 and MPI that was used to
define a group.

#+BEGIN_SRC R :ravel
showClass("snppicker")
#+END_SRC
