% Created 2014-10-13 Mon 11:56
\documentclass[11pt]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{fixltx2e}
\usepackage{graphicx}
\usepackage{longtable}
\usepackage{float}
\usepackage{wrapfig}
\usepackage{rotating}
\usepackage[normalem]{ulem}
\usepackage{amsmath}
\usepackage{textcomp}
\usepackage{marvosym}
\usepackage{wasysym}
\usepackage{amssymb}
\usepackage{hyperref}
\tolerance=1000
\usepackage{fullpage}
\author{Chris Wallace}
\date{2013-12-03 Tue}
\title{GUESSFM: using GUESS for Fine Mapping}
\hypersetup{
  pdfkeywords={},
  pdfsubject={},
  pdfcreator={Emacs 24.3.1 (Org mode 8.2.7c)}}
\begin{document}

\maketitle
\tableofcontents

%\VignetteIndexEntry{GUESSFM Introduction}

\section{Introduction}
\label{sec-1}

\href{http://www.bgx.org.uk/software/guess.html}{GUESS} is software for Bayesian variable selection and model averaging
using a stochastic search algorithm to visit the most likely models
via MCMC.  There also exists an R package, \href{http://cran.r-project.org/web/packages/R2GUESS/index.html}{R2GUESS}, which is a wrapper
for running GUESS, and provides useful diagnostic and summary
functions.

This package, GUESSFM, aims to extend GUESS for fine mapping, defined
here as the task of identifying the most likely set of causal
variants.  The are particular challenges for fine mapping, mostly
related to the density of SNP markers.  Nonetheless, this vignette
will at first focus on an example dataset that comes with R2GUESS.

\section{R2GUESS Strategy}
\label{sec-2}

Although GUESS uses g-priors, which inhibits visiting models with SNPs
in high LD, we have found that running GUESS with SNPs in complete LD
can lead to instability.  R2GUESS was created purely to allow running
GUESS on a tagged set of SNPs to approximate the posterior model
space, and then expand the most interesting models to include their
tags.  It is perhaps useful to give an example of expanding a model.

Suppose we begin tagging, and determine a couple of \emph{tag groups} as follows:

\begin{center}
\begin{tabular}{ll}
Tag & SNPs in tag group\\
$A$ & $A_1$, $A_2$\\
$B$ & $B_1$\\
\end{tabular}
\end{center}

R2GUESS will remove SNPs A1, A2 and B1, and will save a file
containing an object of class \texttt{tags} containting the information in
the above table.  Then, suppose after GUESS has run on the set of tag
SNPs, model $(A,B)$ is one of the most interesting.  GUESS FM will
`expand' this model to the set of models ${(A,B), (A_1,B), (A_2,B),
(A,B_1), (A_1,B_1), (A_2,B_1)}$.  

We assess each model using Bayes Factors.  The Bayes Factor for model
$M_i$ is 

$$BF_{i0} = \frac{P(M_i | \text{data} )}{P(M_0 | \text{data})}.$$

In a fully Bayesian analysis, the individual model
probabilities are calculated by integrating over prior distributions
for the model parameters (regression coefficients, for example).  This
is what GUESS does.  However, it assumes a linear model when often we
will want to fine map a disease trait and therefore use a logistic
model.  Further, we cannot go back and run the expanded models through
GUESS.  Instead, we use Approximate Bayes Factors, based on the BIC:

$$-2 \log{ABF_{i0}} = BIC(M_i) - BIC(M_0).$$

These are calculated within R via the \texttt{glm} and \texttt{BIC} functions.  

At what threshold should you tag?  Probably, as high as you can go
without inducing instability in GUESS.  We have found $r^2=0.99$ to
work in some large datasets, but your mileage may vary.  In the
examples below we use a lower threshold purely for demonstration.

\section{Simulate some data}
\label{sec-3}

We start with using some sample data from the snpStats package
including 20 SNPs, and simulating a quantitative trait that depends
on 3 causal SNPs.

<<>>=
library(snpStats)
data(for.exercise, package="snpStats")
set.seed(12346)
X <- snps.10[,101:120]
n <- nrow(X)
causal <- c("rs1555897","rs7069505")
Y <- rnorm(n,mean=as.numeric(X[,causal[1]]))*sqrt(0.2) +
  rnorm(n,mean=as.numeric(X[,causal[2]]))*sqrt(0.2) +
  rnorm(n)*sqrt(0.6)
@ %def

\texttt{X} contains some missing genotypes, but no SNPs with such a low call
rate we would worry in a large study. Still, the rest of the analysis
is easier to interpret for the purposes of a vignette if we fill in
the missing values.

<<>>=
library(GUESSFM)
summary(col.summary(X))
X <- impute.missing(X)
summary(col.summary(X))
@ %def

Looking at the LD, we see this is a region in which D' (above the
diagonal) is typically high, whilst $r^2$ can be high between some SNPs,
and with moderately strong $r^2 \simeq 0.7$ between two of our causal
SNPs:
<<>>=
ld <- show.ld(X=X)
@ %def


\section{Running GUESS and reading output}
\label{sec-4}

First, via GUESSFM's wrapper, tagging at $r^2=0.8$.  This is
considerably lower than suggested above, and is used here purely for
demonstration as there is limited strong LD in this dataset.

\begin{verbatim}
## THIS DIRECTORY WILL HOLD ALL THE GUESS INPUT AND OUTPUT 
## AND WILL BE CREATED IF IT DOESN'T ALREADY EXIST
mydir <- tempfile() 
## NB, IF GUESS IS NOT ON YOUR PATH, SUPPLY THE FULL PATH IN AN ARGUMENT
## guess.command="/path/to/GUESS"
run.bvs(X,Y,gdir=mydir,backend="guess",tag.r2=0.8,guess.command="/home/chrisw/GUESS_v1.1/Main/GUESS") 
\end{verbatim}


\begin{verbatim}
## THIS CAN TAKE A WHILE.  FOR THE PURPOSES OF THIS VIGNETTE, 
## WE WILL LOAD THE RESULTS FROM AN EXISTING RUN.
mydir <-  system.file("inst","extdata",package="GUESSFM")

## what files were created?
list.files(mydir)

## read output with GUESSFM
d <- read.snpmod(mydir)

## examine the best models and SNPs with greatest marginal support within the tagged data.
best.models(d)
best.snps(d)
\end{verbatim}


Note that both \texttt{best.models} and \texttt{best.snps} allow you to specify thresholds for
how to determine "best".  See their help pages for details.

The tags created within the \texttt{run.bvs} function are saved to a
\texttt{tags.RData} file under \texttt{mydir} and can be examined.

<<>>=
(load(file.path(mydir,"tags.RData")))
tags
@ %def

\begin{enumerate}
\item {\bfseries\sffamily TODO} Which SNPs were selected as tags, esp in relation to causal variants?  Which SNPs come up in the GUESS results?
\label{sec-4-0-0-1}
\end{enumerate}

\section{{\bfseries\sffamily TODO} run via R2GUESS and read output}
\label{sec-5}


You can convert a run from R2GUESS into a snpmod object with:

\begin{verbatim}
## read output using a convenience wrapper for as.ESS.object()
## this returns an object of class ESS, used by R2GUESS
ess <- read.ess(mydir)
str(ess)

## GUESSFM maps snp numbers to names via a decode vector
decode <- structure(colnames(X),names=as.numeric(1:length(X)))

## create a snpmod
gfm2 <- ess2snpmod(ess)
best.models(gfm2)
\end{verbatim}

\section{Expanding}
\label{sec-6}

<<>>=
dx<-expand.tags(d,tags)
@ %def
\section{Plotting}
\label{sec-7}
It is useful to assess the steps of any analysis by looking at the data.  With such
a large number of models, the best way to look is to plot.  For that
reason, GUESSFM contains lots of plotting functions.

?? separate vignette, including vagaries of ggplot?


\section{Parallelism}
\label{sec-8}

Looping over many, many models can be made quicker by parallel
processing.  GUESSFM does this by means of calls to the \texttt{mclapply}
function in the \texttt{parallel} package.  By default, 
the \texttt{parallel} package sets itself up to use two cores.  You can
change this by setting the option \texttt{mc.cores}.  Eg, if you have 20
cores on your machine, you might set
\begin{verbatim}
options(mc.cores=16)
\end{verbatim}
to use 16 of this for R, and leave the remainder free to run other
processes.

Functions which make use of this (and over which you might then not to
use \texttt{mclapply} are: 

\texttt{expand.tags}
% Emacs 24.3.1 (Org mode 8.2.7c)
\end{document}
